export const site = {
  name: "Grafschafter Alltagsservice",
  description: "Anerkannte Alltagshilfe, Haushaltshilfe und Alltagsbegleitung in Moers. Persönliche Betreuung, Entlastung für Angehörige und Unterstützung über die Pflegekasse.",
  url: "https://www.grafschafter-alltagsservice.de",
  owner: "Sokayna Malki",
  streetAddress: "Lippestraße 9L",
  postalCode: "47443",
  locality: "Moers",
  phone: "+49 178 4133757",
  phoneDisplay: "0178 4133757",
  email: "kontakt@grafschafter-alltagsservice.de",
  areaServed: ["Moers","Repelen","Asberg","Kapellen","Meerbeck","Hochstraß","Neukirchen-Vluyn","Kamp-Lintfort","Rheinberg","Duisburg-Homberg","Duisburg-Hochheide","Duisburg-Rheinhausen","Rumeln-Kaldenhausen","Krefeld-Uerdingen"],
  openingHours: "Mo-Fr 08:00-17:00",
  priceRange: "€€",
} as const;
